/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 winnie.gltf --transform
Author: Zoey (https://sketchfab.com/p15227635)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bee-syrup-b7fc7d8361d74438b3cea0cfecc19123
Title: Bee Syrup
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/winnie-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.99, 7.36, 0]} rotation={[Math.PI / 2, 0.02, -Math.PI]} scale={.22}>
        <group position={[-3.4, -6.3, -1.29]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.defaultMat} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.defaultMat} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/winnie-transformed.glb')
